#!/usr/bin/env python3
"""Convert a mono square-wave WAV into TinyTextOS PC-speaker note data."""

import sys
import wave


def estimate_window_frequency(samples, sample_rate):
    amplitude = sum(abs(sample - 128) for sample in samples) / len(samples)

    if amplitude < 10:
        return 0

    transitions = 0
    last = samples[0] >= 128

    for sample in samples[1:]:
        current = sample >= 128

        if current != last:
            transitions += 1
            last = current

    if transitions < 3:
        return 0

    seconds = len(samples) / sample_rate
    frequency = transitions / (2 * seconds)

    if frequency < 40:
        return 0

    return int(round(frequency / 5) * 5)


def merge_events(events):
    merged = []

    for frequency, ticks in events:
        if ticks <= 0:
            continue

        if merged and abs(merged[-1][0] - frequency) <= 10:
            previous_frequency, previous_ticks = merged[-1]
            merged[-1] = (previous_frequency, previous_ticks + ticks)
        else:
            merged.append((frequency, ticks))

    cleaned = []

    for frequency, ticks in merged:
        if cleaned and ticks <= 5 and frequency != 0:
            previous_frequency, previous_ticks = cleaned[-1]
            cleaned[-1] = (previous_frequency, previous_ticks + ticks)
        else:
            cleaned.append((frequency, ticks))

    final = []

    for frequency, ticks in cleaned:
        if final and final[-1][0] == frequency:
            previous_frequency, previous_ticks = final[-1]
            final[-1] = (previous_frequency, previous_ticks + ticks)
        else:
            final.append((frequency, ticks))

    return final


def convert(input_path, output_path):
    with wave.open(input_path, "rb") as wav:
        if wav.getnchannels() != 1 or wav.getsampwidth() != 1:
            raise SystemExit("Song WAV must be 8-bit mono PCM.")

        sample_rate = wav.getframerate()
        samples = wav.readframes(wav.getnframes())

    window_size = max(1, sample_rate // 20)
    events = []

    for start in range(0, len(samples), window_size):
        window = samples[start:start + window_size]

        if len(window) < window_size // 2:
            break

        frequency = estimate_window_frequency(window, sample_rate)
        ticks = int(round((len(window) / sample_rate) * 100))
        events.append((frequency, ticks))

    events = merge_events(events)

    with open(output_path, "w", encoding="utf-8", newline="\n") as output:
        output.write("/* Generated by generate_song.py. Do not edit by hand. */\n\n")
        output.write("#define SONG_NOTE_COUNT %d\n\n" % len(events))
        output.write("static const u16 song_notes[SONG_NOTE_COUNT][2] =\n")
        output.write("{\n")

        for frequency, ticks in events:
            output.write("    {%d, %d},\n" % (frequency, ticks))

        output.write("};\n")


def main():
    if len(sys.argv) != 3:
        raise SystemExit("Usage: generate_song.py input.wav output.h")

    convert(sys.argv[1], sys.argv[2])


if __name__ == "__main__":
    main()
