/* Generated by generate_song.py. Do not edit by hand. */

#define SONG_NOTE_COUNT 7

static const u16 song_notes[SONG_NOTE_COUNT][2] =
{
    {260, 50},
    {0, 5},
    {330, 50},
    {0, 5},
    {390, 55},
    {520, 70},
    {0, 5},
};
